name: Build and test addon

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  buildAndTest:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scons
        pip install Markdown
        pip install flake8
        pip install flake8-tabs
    - name: Build artifact path
      run: mkdir -p artifactPath
    - name: Lint push with flake8
      if: github.event_name == 'push'
      run:
        flake8 --config .github/extra_resources/setup.cfg --output-file="artifactPath\flake8.txt" --tee --exit-zero addon
    - name: Lint pull request with flake8
      if: github.event_name == 'pull_request'
      run: |
        git fetch origin
        git diff -u origin/${{ github.event.pull_request.base.ref }} | flake8 --diff --config .github/extra_resources/setup.cfg --output-file="artifactPath\flake8.txt" --tee --exit-zero 
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build add-on
      run: scons
    - name: Copy addon
      run: |
        move *.nvda-addon addon.zip
        expand-archive addon.zip $env:appdata\nvda\addons\addon
    - name: Download NVDA
      run: curl --location --output stable.exe https://addons.nvda-project.org/files/get.php?file=nvda
    - name: Install NVDA
      run: stable.exe --install-silent
      shell: cmd
    - name: start nvda
      #run: start nvda -m -f %TEMP%\nvda-with-addon.log --debug-logging
      run: start nvda -m --debug-logging
      shell: cmd
    - name: Quit NVDA
      run: start nvda -r
      shell: cmd
    - name: get the log file from temp directory
      #shell: cmd
      #run: .github/extra_resources/move_locked_file.bat %temp%\nvda-with-addon.log artifactPath\nvda.log
      shell: python
      run: |
        import os, tempfile
        path = os.path.join(tempfile.gettempdir(), "nvda-old.log")
        os.rename(path, os.path.join(os.path.dirname(__file__), "artifactPath", "nvda.log"))
    - name: Upload NVDA's log and flake8 results
      uses: actions/upload-artifact@v1
      with:
        name: nvda.log and flake8
        path: artifactPath
