name: Build and test addon

on:
  push:
  pull_request:
    types:
      - opened
      - reopened
      - edited
      - synchronize

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scons
        pip install Markdown
        pip install flake8
        pip install flake8-tabs
    - name: Lint push with flake8
      if: github.event_name == 'push'
      run:
        flake8 --config .github/extra_resources/setup.cfg --exit-zero addon
    - name: Lint pull request with flake8
      if: github.event_name == 'pull_request'
      run:
        curl ${{ github.event.pull_request.diff_url }} | flake8 --diff --config .github/extra_resources/setup.cfg --exit-zero 
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build add-on
      run: scons
    - name: Copy addon
      run: |
        move *.nvda-addon addon.zip
        expand-archive addon.zip '%APPDATA%\nvda\addons\addon'
    - name: Download NVDA
      run: curl --location --output stable.exe https://addons.nvda-project.org/files/get.php?file=nvda
    - name: Install NVDA
      run: |
        stable.exe --install -m -f nvda.log --debug-logging
        dir %temp%
      shell: cmd
    - name: Quit NVDA
      run: start nvda -q
      shell: cmd
    - name: get the log file from temp directory
      shell: cmd
      run: |
        ping 192.0.2.0 -n 1 -w 10000 > nul
        copy %TEMP%\nvda.log nvda.log
    - name: Upload NVDA's log
      uses: actions/upload-artifact@v1
      with:
        name: NVDA-log
        path: nvda.log
