name: Build and test addon

on:
  pull_request:
    types:
      - edited
      - opened
      - reopened
      - synchronize

jobs:
  syntaxAndCodeStyle:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scons
        pip install Markdown
        pip install flake8
        pip install flake8-tabs
    - name: Lint push with flake8
      if: github.event_name == 'push'
      run:
        flake8 --config .github/extra_resources/setup.cfg --output-file="flake8.txt" --tee addon
    - name: Lint pull request with flake8
      if: github.event_name == 'pull_request'
      run: |
        git fetch origin
        git diff -u origin/${{ github.event.pull_request.base.ref }} | flake8 --diff --config .github/extra_resources/setup.cfg --output-file="flake8.txt" --tee  
    - name: Upload flake8 output as artifact
      uses: actions/upload-artifact@v1
      with:
        name: flake8.txt
        path: flake8.txt

  buildAndTestWithNVDA:
    needs: syntaxAndCodeStyle
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scons
        pip install Markdown
    - name: Build add-on
      run: scons
    - name: Copy addon
      run: |
        move *.nvda-addon addon.zip
        expand-archive addon.zip $env:appdata\nvda\addons\addon
    - name: Download NVDA
      run: curl --location --output stable.exe https://addons.nvda-project.org/files/get.php?file=nvda
    - name: Install NVDA
      run: stable.exe --install-silent
      shell: cmd
    - name: start nvda
      run: start nvda -m --debug-logging
      shell: cmd
    - name: restart NVDA, so that the lock on the current logfile can be freed
      run: start nvda -r
      shell: cmd
    - name: get a copy of the nvda-old.log
      shell: cmd
      run: move %TEMP%\nvda-old.log .
    - name: Upload nvda-old.log
      uses: actions/upload-artifact@v1
      with:
        name: nvda-old.log
        path: nvda-old.log
