name: comment-on-pr example
on: pull_request
jobs:
  example:
    name: sample comment
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      id: main
      uses: actions/checkout@v2
      with:
        path: main
    - name: checkout template
      id: template
      uses: actions/checkout@v2
      with:
        repository: nvdaaddons/AddonTemplate
        path: addonTemplate
    - name: check sconstructs file
      id: sconstruct
      run: |
        diff -u addonTemplate/sconstruct main/sconstruct
    - name: check style file
      id: style
      run: |
        diff -u addonTemplate/style.css main/style.css
    - name: check site_scons directory
      id: site_scons
      run: |
        diff -ur addonTemplates/site_scons main/site_scons
    - name: comment PR
      if: failure()
      uses: unsplash/comment-on-pr@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        msg: "This pull request doesnt seem to have the latest addon template!"
