name: Install add-on and run NVDA

on: [push]

jobs:
  installAddon:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Copy addon
      run: move addon nvda\userConfig\addons
    - name: Run NVDA
      run: nvda\nvda.exe -f nvda.log --debug-logging
    - name: Quit NVDA
      run: nvda -q
    - name: Upload NVDA's log
      uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: nvda\nvda.log
