name: Lint markdown files

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node
      uses: actions/setup-node@v1
    - name: Lint
      run: |
        npm install -g markdownlint-cli
        markdownlint **/*.md --ignore node_modules
