name: Build and test addon with NVDA's plugin

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install scons
        pip install Markdown
        pip install flake8
        pip install flake8-tabs
    - name: Lint with flake8
      run:
        flake8 --config .github/extra_resources/setup.cfg --exit-zero addon
        # stop the build if there are Python syntax errors or undefined names
        # flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        # flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Build add-on
      run: scons
    - name: Copy NVDA resources
      run: |
        move *.nvda-addon addon.zip
        expand-archive addon.zip $env:appdata\nvda\addons\addon
        move .github\extra_resources\nvda.ini $env:appdata\nvda\nvda.ini
        move .github\extra_resources\globalPlugins $env:appdata\nvda\scratchpad\globalPlugins
    - name: Download NVDA
      run: curl --location --output stable.exe https://addons.nvda-project.org/files/get.php?file=nvda
    - name: Install NVDA
      run: stable.exe --install-silent
      shell: cmd
    - name: Create artifact path
      mkdir: artifactPath
    - name: start nvda
      run: start nvda -m --debug-logging
      shell: cmd
    - name: Quit NVDA
      run: start nvda -q
      shell: cmd
    - name: Upload NVDA's log
      uses: actions/upload-artifact@v2-preview
      with:
        name: 'nvda.log'
        path: artifactPath
